### ISSUE TITLE
メールのYouTubeにサムネイル画像入れる

### ISSUE THREAD

**Issue by yshiga** [yshiga/bee-news-jp-client#24]
ついでに、動画に何も表示されないバグを治す
![image](https://cloud.githubusercontent.com/assets/3081193/16474220/a9033fc4-3e29-11e6-963f-65e5ec184536.png)

**Comment by yshiga** [comment]
YouTubeのサムネイルが表示されない。 (Facebookは表示されても)
![image](https://cloud.githubusercontent.com/assets/3081193/16825146/fe438b3a-4926-11e6-9f69-1c1c8a2bf460.png)

**Comment by jun-oka** [comment]
再調整中です！

**Comment by jun-oka** [comment]
I'm working this now
